spring:
  application:
    name: API for Academy Account
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false

server:
  port: 8080

logging:
  level:
    root: INFO
    io.github.caliburno.academy_accounting: DEBUG
